package main

import (
	"context"
	"flag"
	"fmt"
	"net/http"
	"net/http/pprof"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	log "github.com/sirupsen/logrus"

	_ "k8s.io/client-go/plugin/pkg/client/auth"

	"github.com/jenkins-x/exposecontroller/controller"
	"github.com/jenkins-x/exposecontroller/version"
	"github.com/spf13/pflag"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/cli-runtime/pkg/genericclioptions"
	"k8s.io/client-go/kubernetes"
	//"k8s.io/client-go/tools/clientcmd"
	kubectlutil "k8s.io/kubectl/pkg/cmd/util"
	"k8s.io/kubectl/pkg/scheme"
)

const (
	healthPort = 10254
)

var (
	flags = pflag.NewFlagSet("", pflag.ExitOnError)

	configFile = flags.String("config", "/etc/exposecontroller/config.yml",
		`Path to the file that contains the exposecontroller configuration to use`)

	resyncPeriod = flags.Duration("sync-period", 30*time.Second,
		`Relist and confirm services this often.`)

	healthzPort = flags.Int("healthz-port", healthPort, "port for healthz endpoint.")

	profiling = flags.Bool("profiling", true, `Enable profiling via web interface host:port/debug/pprof/`)

	daemon  = flag.Bool("daemon", false, `Run as daemon mode watching changes as it happens.`)
	cleanup = flag.Bool("cleanup", false, `Removes Ingress rules that were generated by exposecontroller`)

	domain                = flag.String("domain", "", "Domain to use with your DNS provider (default: .nip.io).")
	filter                = flag.String("filter", "", "The filter of service names to look for when cleaning up")
	exposer               = flag.String("exposer", "", "Which strategy exposecontroller should use to access applications")
	apiserver             = flag.String("api-server", "", "API server URL")
	consoleurl            = flag.String("console-server", "", "Console URL")
	httpb                 = flag.Bool("http", false, `Use HTTP`)
	watchNamespaces       = flag.String("watch-namespace", "", "Exposecontroller will only look at the provided namespace")
	watchCurrentNamespace = flag.Bool("watch-current-namespace", true, `Exposecontroller will look at the current namespace only - (default: 'true' unless --watch-namespace specified)`)
	services              = flag.String("services", "", "List of comma separated service names which will be exposed, if empty all services from namespace will be considered")
)

func main() {
	kubeConfigFlags := genericclioptions.NewConfigFlags(true).WithDeprecatedPasswordFlag()
	factory := kubectlutil.NewFactory(kubeConfigFlags)

	kubeConfigFlags.AddFlags(flags)
	flags.AddGoFlagSet(flag.CommandLine)

	flags.Parse(os.Args)

	log.Infof("Using build: %v", version.Version)

	clientset, err := factory.KubernetesClientSet()
	for i := 0; i < 30; i++ {
		if err != nil {
			log.Warningf("failed to create clientset, retrying: %s", err)
			time.Sleep(1 * time.Second)
			clientset, err = factory.KubernetesClientSet()
		} else {
			break
		}
	}
	if err != nil {
		log.Fatalf("failed to create clientset: %s", err)
		panic(err)
	}

	encoder := scheme.DefaultJSONEncoder()
	if encoder == nil {
		log.Fatalf("encoder is nil")
		panic(err)
	}

	currentNamespace := os.Getenv("KUBERNETES_NAMESPACE")
	if len(currentNamespace) == 0 {
		/*
					 * TODO, get de default/current namespace
			                currentNamespace, _, err = clientset.Namespace()
			                if err != nil {
			                        log.Fatalf("Could not find the current namespace: %v", err)
			                }
		*/
	}

	controllerConfig, exists, err := controller.LoadFile(*configFile)
	if !exists || err != nil {
		if err != nil {
			log.Warningf("failed to load config file: %s", err)
		}

		cc2 := tryFindConfig(clientset, currentNamespace)
		if cc2 == nil {
			// lets try find the ConfigMap in the dev namespace
			resource, err := clientset.CoreV1().Namespaces().Get(context.TODO(), currentNamespace, metav1.GetOptions{})
			if err == nil && resource != nil {
				labels := resource.Labels
				if labels != nil {
					ns := labels["team"]
					if ns == "" {
						log.Warningf("No 'team' label on Namespace %s", currentNamespace)
					} else {
						log.Printf("trying to find the ConfigMap in the Dev Namespace %s", ns)

						cc2 = tryFindConfig(clientset, ns)
					}
				} else {
					log.Warningf("No labels on Namespace %s", currentNamespace)
				}
			} else {
				log.Warningf("Failed to load Namespace %s: %s", currentNamespace, err)

				// lets try default to trimming the lasts path from the current namespace
				idx := strings.LastIndex(currentNamespace, "-")
				if idx > 1 {
					ns := currentNamespace[0:idx]
					cc2 = tryFindConfig(clientset, ns)
				}
			}
		}
		if cc2 != nil {
			controllerConfig = cc2
		}
	} else {
		log.Printf("Loaded config file %s", *configFile)
	}

	log.Printf("Config file before overrides:\n%s", controllerConfig.String())

	if *domain != "" {
		controllerConfig.Domain = *domain
	}
	if *exposer != "" {
		controllerConfig.Exposer = *exposer
	}
	if *apiserver != "" {
		controllerConfig.ApiServer = *apiserver
	}
	if *consoleurl != "" {
		controllerConfig.ConsoleURL = *consoleurl
	}
	if *httpb {
		controllerConfig.HTTP = *httpb
	}

	if *watchCurrentNamespace {
		controllerConfig.WatchCurrentNamespace = *watchCurrentNamespace
	}
	if *watchNamespaces != "" {
		controllerConfig.WatchNamespaces = *watchNamespaces
		controllerConfig.WatchCurrentNamespace = false
	}

	if *services != "" {
		controllerConfig.Services = strings.Split(*services, ",")
	}

	log.Printf("Config file after overrides:\n%s", controllerConfig.String())

	//watchNamespaces := api.NamespaceAll
	watchNamespaces := controllerConfig.WatchNamespaces
	if controllerConfig.WatchCurrentNamespace {
		if len(currentNamespace) == 0 {
			log.Fatalf("No current namespace found!")
		}
		watchNamespaces = currentNamespace
	}

	if *cleanup {
		ingress, err := clientset.ExtensionsV1beta1().Ingresses(watchNamespaces).List(context.TODO(), metav1.ListOptions{})
		if err != nil {
			log.Fatalf("Could not get ingress rules in namespace %s %v", watchNamespaces, err)
		}

		for _, i := range ingress.Items {
			if i.Annotations["fabric8.io/generated-by"] == "exposecontroller" {
				if filter == nil || strings.Contains(i.Name, *filter) {
					log.Infof("Deleting ingress %s", i.Name)
					err := clientset.ExtensionsV1beta1().Ingresses(watchNamespaces).Delete(context.TODO(), i.Name, metav1.DeleteOptions{})
					if err != nil {
						log.Fatalf("Could not find the current namespace: %s", err)
					}
				}
			}
		}
		return
	}

	if *daemon {
		log.Printf("Watching services in namespaces: `%s`", watchNamespaces)

		c, err := controller.NewController(clientset, encoder, *resyncPeriod, watchNamespaces, controllerConfig)
		if err != nil {
			log.Fatalf("%s", err)
		}

		go registerHandlers()
		go handleSigterm(c)

		c.Run()
	} else {
		log.Infof("Running in : `%s`", watchNamespaces)
		c, err := controller.NewController(clientset, encoder, *resyncPeriod, watchNamespaces, controllerConfig)
		if err != nil {
			log.Fatalf("%s", err)
		}

		ticker := time.NewTicker(5 * time.Second)
		quit := make(chan struct{})
		go func() {
			for {
				select {
				case <-ticker.C:
					if c.Hasrun() {
						close(quit)
					}
				case <-quit:
					c.Stop()
					ticker.Stop()
					return
				}
			}
		}()
		// Handle Control-C has well here
		go handleSigterm(c)

		c.Run()
	}
}

func tryFindConfig(clientset *kubernetes.Clientset, ns string) *controller.Config {
	var controllerConfig *controller.Config
	cm, err := clientset.CoreV1().ConfigMaps(ns).Get(context.TODO(), "exposecontroller", metav1.GetOptions{})
	if err == nil {
		log.Infof("Using ConfigMap exposecontroller to load configuration...")
		// TODO we could allow the config to be passed in via key/value pairs?
		text := cm.Data["config.yml"]
		if text != "" {
			controllerConfig, err = controller.Load(text)
			if err != nil {
				log.Warningf("Could not parse the config text from exposecontroller ConfigMap %s", err)
			}
			log.Infof("Loaded ConfigMap exposecontroller to load configuration!")
		}
	} else {
		log.Warningf("Could not find ConfigMap exposecontroller ConfigMap in namespace %s", ns)

		cm, err = clientset.CoreV1().ConfigMaps(ns).Get(context.TODO(), "ingress-config", metav1.GetOptions{})
		if err != nil {
			log.Warningf("Could not find ConfigMap ingress-config ConfigMap in namespace %s", ns)
		} else {
			log.Infof("Loaded ConfigMap ingress-config to load configuration!")
			data := cm.Data
			if data != nil {
				controllerConfig, err = controller.MapToConfig(data)
				if err != nil {
					log.Warningf("Failed to convert Map data %#v from configMap ingress-config in namespace %s due to: %s\n", controllerConfig, ns, err)
				}
			}
		}
	}
	return controllerConfig
}

func registerHandlers() {
	mux := http.NewServeMux()

	if *profiling {
		mux.HandleFunc("/debug/pprof/", pprof.Index)
		mux.HandleFunc("/debug/pprof/profile", pprof.Profile)
		mux.HandleFunc("/debug/pprof/symbol", pprof.Symbol)
	}

	server := &http.Server{
		Addr:    fmt.Sprintf(":%v", *healthzPort),
		Handler: mux,
	}
	log.Fatal(server.ListenAndServe())
}

func handleSigterm(c *controller.Controller) {
	signalChan := make(chan os.Signal, 1)
	signal.Notify(signalChan, syscall.SIGINT, syscall.SIGTERM)
	sig := <-signalChan
	log.Infof("Received %s, shutting down", sig)
	c.Stop()
}
