{{- if .Values.config }}
apiVersion: v1
data:
  config.yml: |-
{{- if .Values.config.exposer }}
    exposer: {{ .Values.config.exposer  }}
{{- end }}
{{- if .Values.config.domain }}
    domain: {{ .Values.config.domain }}
{{- end }}
{{- if  .Values.config.http }}
    http: {{  .Values.config.http }}
{{- end }}
    tls-acme: {{ .Values.config.tlsacme | default false  }}
kind: ConfigMap
metadata:
  name: exposecontroller
{{- end }}