Image: "gcr.io/jenkinsxio/exposecontroller"
ImageTag: "latest"
BackoffLimit: 5
Annotations: {}

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi

  # use value of `path` to use path based ingress
# config:
#   pathMode: "path"
#   tlsacme: true
#   extravalues:
#     foo: bar

# Args:
#   - --help

# To use exposecontroller you probably want to enable it in helm hooks, here's an example values.yaml:

# annotations:
#   helm.sh/hook: post-install
#   helm.sh/hook-delete-policy: hook-succeeded

# cleanup:
#   annotations:
#     helm.sh/hook: pre-delete
#     helm.sh/hook-delete-policy: hook-succeeded
#   args: [--cleanup]
